const wordStock = [
  {
    word1: "awful",
    word2: "terrible",
    correct: true,
    translation: "ужасный",
  },
  {
    word1: "truth",
    word2: "lie",
    correct: false,
    translation: "правда",
  },
  {
    word1: "vehicle",
    word2: "car",
    correct: true,
    translation: "автомобиль",
  },
  {
    word1: "trustworthy",
    word2: "reliable",
    correct: true,
    translation: "надёжный",
  },
  {
    word1: "stomach",
    word2: "belly",
    correct: true,
    translation: "живот",
  },
  {
    word1: "march",
    word2: "run",
    correct: false,
    translation: "маршировать",
  },
  {
    word1: "make",
    word2: "create",
    correct: true,
    translation: "сделать",
  },
  {
    word1: "observe",
    word2: "listen",
    correct: false,
    translation: "наблюдать",
  },
  {
    word1: "fallacy",
    word2: "error",
    correct: true,
    translation: "ошибка",
  },
  {
    word1: "transparent",
    word2: "dark",
    correct: false,
    translation: "прозрачный",
  },
  {
    word1: "relative",
    word2: "ancestor",
    correct: true,
    translation: "родитель",
  },
  {
    word1: "withdraw",
    word2: "extract",
    correct: true,
    translation: "извлекать",
  },
  {
    word1: "alphabetical",
    word2: "numerous",
    correct: false,
    translation: "алфавитный",
  },
  {
    word1: "hilarious",
    word2: "advantageous",
    correct: false,
    translation: "смешной",
  },
  {
    word1: "ostensible",
    word2: "showy",
    correct: true,
    translation: "показной",
  },
  {
    word1: "print",
    word2: "check",
    correct: false,
    translation: "печатать",
  },
  {
    word1: "vulgar",
    word2: "banal",
    correct: true,
    translation: "пошлый",
  },
  {
    word1: "case",
    word2: "accident",
    correct: true,
    translation: "случай",
  },
  {
    word1: "senior",
    word2: "major",
    correct: true,
    translation: "главный",
  },
  {
    word1: "senile",
    word2: "young",
    correct: false,
    translation: "старческий",
  },
  {
    word1: "prohibit",
    word2: "ban",
    correct: true,
    translation: "запрещать",
  },
  {
    word1: "fall",
    word2: "rise",
    correct: false,
    translation: "падение",
  },
  {
    word1: "piss",
    word2: "beat",
    correct: false,
    translation: "мочиться",
  },
  {
    word1: "tackle",
    word2: "snitch",
    correct: false,
    translation: "взяться",
  },
  {
    word1: "obtrusive",
    word2: "intrusive",
    correct: true,
    translation: "назойливый",
  },
  {
    word1: "aspire",
    word2: "strive",
    correct: true,
    translation: "стремиться",
  },
  {
    word1: "secular",
    word2: "worldly",
    correct: true,
    translation: "светский",
  },
  {
    word1: "lawyer",
    word2: "prosecutor",
    correct: false,
    translation: "адвокат",
  },
  {
    word1: "convict",
    word2: "judge",
    correct: true,
    translation: "судить",
  },
  {
    word1: "delude",
    word2: "excuse",
    correct: false,
    translation: "заблуждать",
  },
  {
    word1: "flamboyant",
    word2: "colourful",
    correct: true,
    translation: "цветистый",
  },
  {
    word1: "demonstrative",
    word2: "visual",
    correct: true,
    translation: "показательный",
  },
  {
    word1: "raise",
    word2: "lift",
    correct: true,
    translation: "поднимать",
  },
  {
    word1: "impetuous",
    word2: "lazy",
    correct: false,
    translation: "стремительный",
  },
  {
    word1: "salary",
    word2: "wage",
    correct: true,
    translation: "зарплата",
  },
  {
    word1: "girlish",
    word2: "masculine",
    correct: false,
    translation: "девчачий",
  },
  {
    word1: "cup",
    word2: "mug",
    correct: true,
    translation: "кружка",
  },
  {
    word1: "traffic",
    word2: "mystery",
    correct: false,
    translation: "движение",
  },
  {
    word1: "simple",
    word2: "usual",
    correct: true,
    translation: "простой",
  },
  {
    word1: "assigned",
    word2: "designated",
    correct: true,
    translation: "назначенный",
  },
  {
    word1: "restrict",
    word2: "limit",
    correct: true,
    translation: "ограничивать",
  },
  {
    word1: "command",
    word2: "demand",
    correct: false,
    translation: "командовать",
  },
  {
    word1: "loyal",
    word2: "faithful",
    correct: true,
    translation: "преданный",
  },
  {
    word1: "canoodle",
    word2: "explain",
    correct: false,
    translation: "ласкаться",
  },
  {
    word1: "love",
    word2: "adore",
    correct: true,
    translation: "любить",
  },
  {
    word1: "invincible",
    word2: "victorious",
    correct: true,
    translation: "непобедимый",
  },
  {
    word1: "deny",
    word2: "reject",
    correct: true,
    translation: "отрицать",
  },
  {
    word1: "lake",
    word2: "alley",
    correct: false,
    translation: "озеро",
  },
  {
    word1: "torturous",
    word2: "painful",
    correct: true,
    translation: "мучительный",
  },
  {
    word1: "discipline",
    word2: "fortitude",
    correct: false,
    translation: "дисциплина",
  },
  {
    word1: "whimsical",
    word2: "fancy",
    correct: true,
    translation: "причудливый",
  },
  {
    word1: "snake",
    word2: "serpent",
    correct: true,
    translation: "змея",
  },
  {
    word1: "prefer",
    word2: "like",
    correct: true,
    translation: "предпочитать",
  },
  {
    word1: "incise",
    word2: "increase",
    correct: false,
    translation: "надрезать",
  },
  {
    word1: "profane",
    word2: "unholy",
    correct: true,
    translation: "нечестивый",
  },
  {
    word1: "whore",
    word2: "artist",
    correct: false,
    translation: "проститутка",
  },
  {
    word1: "select",
    word2: "choose",
    correct: true,
    translation: "выбирать",
  },
  {
    word1: "prophecy",
    word2: "festival",
    correct: false,
    translation: "пророчество",
  },
  {
    word1: "abdication",
    word2: "refusal",
    correct: true,
    translation: "отречение",
  },
  {
    word1: "cheese",
    word2: "cream",
    correct: false,
    translation: "сыр",
  },
  {
    word1: "weight",
    word2: "mass",
    correct: true,
    translation: "вес",
  },
  {
    word1: "transfer",
    word2: "get",
    correct: false,
    translation: "передавать",
  },
  {
    word1: "disgusting",
    word2: "obnoxious",
    correct: true,
    translation: "отвратительный",
  },
  {
    word1: "payment",
    word2: "check",
    correct: false,
    translation: "плата",
  },
  {
    word1: "loss",
    word2: "defeat",
    correct: true,
    translation: "поражение",
  },
  {
    word1: "congratulate",
    word2: "behave",
    correct: false,
    translation: "поздравлять",
  },
  {
    word1: "mannerly",
    word2: "courteous",
    correct: true,
    translation: "вежливый",
  },
  {
    word1: "vegetable",
    word2: "fruit",
    correct: false,
    translation: "овощ",
  },
  {
    word1: "call",
    word2: "invoke",
    correct: true,
    translation: "вызывать",
  },
  {
    word1: "offer",
    word2: "try",
    correct: false,
    translation: "предлагать",
  },
  {
    word1: "endeavor",
    word2: "attempt",
    correct: true,
    translation: "пытаться",
  },
  {
    word1: "plot",
    word2: "beginning",
    correct: false,
    translation: "содержание",
  },
  {
    word1: "seduce",
    word2: "tempt",
    correct: true,
    translation: "соблазнять",
  },
  {
    word1: "war",
    word2: "activity",
    correct: false,
    translation: "война",
  },
  {
    word1: "present",
    word2: "give",
    correct: true,
    translation: "дарить",
  },
  {
    word1: "hard",
    word2: "easy",
    correct: false,
    translation: "сложный",
  },
  {
    word1: "contemplate",
    word2: "think",
    correct: true,
    translation: "думать",
  },
  {
    word1: "fashion",
    word2: "stage",
    correct: false,
    translation: "мода",
  },
  {
    word1: "pleasure",
    word2: "satisfaction",
    correct: true,
    translation: "удовольствие",
  },
  {
    word1: "fast",
    word2: "rapid",
    correct: true,
    translation: "быстрый",
  },
  {
    word1: "occupation",
    word2: "nation",
    correct: false,
    translation: "занятие",
  },
  {
    word1: "country",
    word2: "vicinity",
    correct: false,
    translation: "страна",
  },
  {
    word1: "point",
    word2: "sense",
    correct: true,
    translation: "смысл",
  },
  {
    word1: "benevolent",
    word2: "kind",
    correct: true,
    translation: "доброжелательный",
  },
  {
    word1: "learn",
    word2: "educate",
    correct: false,
    translation: "учить",
  },
  {
    word1: "flirtatious",
    word2: "coquettish",
    correct: true,
    translation: "кокетливый",
  },
  {
    word1: "petrol",
    word2: "gas",
    correct: true,
    translation: "бензин",
  },
  {
    word1: "disappoint",
    word2: "panic",
    correct: false,
    translation: "расстраивать",
  },
  {
    word1: "carnivorous",
    word2: "predator",
    correct: true,
    translation: "хищный",
  },
  {
    word1: "television",
    word2: "radio",
    correct: false,
    translation: "телевидение",
  },
  {
    word1: "place",
    word2: "spot",
    correct: true,
    translation: "место",
  },
  {
    word1: "relationship",
    word2: "status",
    correct: false,
    translation: "отношение",
  },
  {
    word1: "crash",
    word2: "break",
    correct: true,
    translation: "разбивать",
  },
  {
    word1: "water",
    word2: "soup",
    correct: false,
    translation: "вода",
  },
  {
    word1: "dangle",
    word2: "hang",
    correct: true,
    translation: "висеть",
  },
  {
    word1: "kiss",
    word2: "hold",
    correct: false,
    translation: "целовать",
  },
  {
    word1: "movie",
    word2: "film",
    correct: true,
    translation: "кино",
  },
  {
    word1: "align",
    word2: "fix",
    correct: false,
    translation: "выравнивать",
  },
  {
    word1: "dress",
    word2: "wear",
    correct: true,
    translation: "платье",
  },
  {
    word1: "obvious",
    word2: "evident",
    correct: true,
    translation: "очевидный",
  },
  {
    word1: "become",
    word2: "receive",
    correct: false,
    translation: "становиться",
  },
  {
    word1: "wish",
    word2: "desire",
    correct: true,
    translation: "желать",
  },
  {
    word1: "ratio",
    word2: "proportion",
    correct: true,
    translation: "соотношение",
  },
  {
    word1: "scheme",
    word2: "layer",
    correct: false,
    translation: "схема",
  },
  {
    word1: "humanity",
    word2: "cruelty",
    correct: false,
    translation: "человечность",
  },
  {
    word1: "dangerous",
    word2: "outrageous",
    correct: false,
    translation: "опасный",
  },
  {
    word1: "pending",
    word2: "loading",
    correct: false,
    translation: "ожидающий",
  },
  {
    word1: "junior",
    word2: "expert",
    correct: false,
    translation: "младший",
  },
  {
    word1: "humorous",
    word2: "ridiculous",
    correct: true,
    translation: "комический",
  },
  {
    word1: "arrange",
    word2: "schedule",
    correct: true,
    translation: "устраивать",
  },
  {
    word1: "warn",
    word2: "admonish",
    correct: true,
    translation: "предупреждать",
  },
  {
    word1: "valley",
    word2: "forest",
    correct: false,
    translation: "долина",
  },
  {
    word1: "king",
    word2: "royal",
    correct: true,
    translation: "король",
  },
  {
    word1: "urge",
    word2: "hope",
    correct: false,
    translation: "побуждение",
  },
  {
    word1: "hustle",
    word2: "listen",
    correct: false,
    translation: "понуждать",
  },
  {
    word1: "calculate",
    word2: "compute",
    correct: true,
    translation: "считать",
  },
  {
    word1: "machine",
    word2: "freezer",
    correct: false,
    translation: "машина",
  },
  {
    word1: "fulfil",
    word2: "execute",
    correct: true,
    translation: "выполнять",
  },
  {
    word1: "procedure",
    word2: "mechanism",
    correct: false,
    translation: "процедура",
  },
  {
    word1: "remind",
    word2: "assasinate",
    correct: true,
    translation: "напомнить",
  },
  {
    word1: "forget",
    word2: "reminisce",
    correct: false,
    translation: "забывать",
  },
  {
    word1: "beautiful",
    word2: "gorgeous",
    correct: true,
    translation: "красивый",
  },
  {
    word1: "bring",
    word2: "carry",
    correct: true,
    translation: "приносить",
  },
  {
    word1: "glorious",
    word2: "famous",
    correct: true,
    translation: "славный",
  },
  {
    word1: "charming",
    word2: "enchanting",
    correct: true,
    translation: "очаровательный",
  },
  {
    word1: "procrastinate",
    word2: "perform",
    correct: false,
    translation: "отсрочивать",
  },
  {
    word1: "sign",
    word2: "retire",
    correct: false,
    translation: "подписываться",
  },
  {
    word1: "reward",
    word2: "prize",
    correct: true,
    translation: "награда",
  },
  {
    word1: "ravishing",
    word2: "stubborn",
    correct: false,
    translation: "восхитительный",
  },
  {
    word1: "rest",
    word2: "relax",
    correct: true,
    translation: "отдыхать",
  },
  {
    word1: "towering",
    word2: "short",
    correct: false,
    translation: "высокий",
  },
  {
    word1: "lean",
    word2: "rely",
    correct: true,
    translation: "опираться",
  },
  {
    word1: "research",
    word2: "stumble",
    correct: false,
    translation: "исследовать",
  },
  {
    word1: "defend",
    word2: "protect",
    correct: true,
    translation: "защищать",
  },
  {
    word1: "access",
    word2: "accept",
    correct: false,
    translation: "доступ",
  },
  {
    word1: "eliminate",
    word2: "prevent",
    correct: true,
    translation: "предотвращать",
  },
  {
    word1: "excellent",
    word2: "cognitive",
    correct: false,
    translation: "превосходный",
  },
  {
    word1: "encounter",
    word2: "face",
    correct: true,
    translation: "сталкиваться",
  },
  {
    word1: "ruler",
    word2: "mentor",
    correct: false,
    translation: "линейка",
  },
  {
    word1: "messy",
    word2: "dirty",
    correct: true,
    translation: "грязный",
  },
  {
    word1: "road",
    word2: "way",
    correct: true,
    translation: "дорога",
  },
  {
    word1: "huge",
    word2: "enormous",
    correct: true,
    translation: "огромный",
  },
  {
    word1: "fit",
    word2: "mental",
    correct: false,
    translation: "здоровый",
  },
  {
    word1: "genetics",
    word2: "figure",
    correct: false,
    translation: "генетика",
  },
  {
    word1: "suggest",
    word2: "suppose",
    correct: false,
    translation: "предлагать",
  },
  {
    word1: "assume",
    word2: "theorize",
    correct: true,
    translation: "предполагать",
  },
  {
    word1: "adopt",
    word2: "abandon",
    correct: false,
    translation: "усыновлять",
  },
  {
    word1: "expect",
    word2: "besides",
    correct: false,
    translation: "ожидать",
  },
  {
    word1: "gleam",
    word2: "blink",
    correct: true,
    translation: "мерцать",
  },
  {
    word1: "coach",
    word2: "trainer",
    correct: true,
    translation: "тренер",
  },
  {
    word1: "extraordinary",
    word2: "amazing",
    correct: false,
    translation: "нестандартный",
  },
  {
    word1: "trousers",
    word2: "pants",
    correct: true,
    translation: "брюки",
  },
  {
    word1: "hollow",
    word2: "emptiness",
    correct: true,
    translation: "пустота",
  },
  {
    word1: "guide",
    word2: "follow",
    correct: false,
    translation: "направлять",
  },
  {
    word1: "prisoner",
    word2: "secretary",
    correct: false,
    translation: "узник",
  },
  {
    word1: "juicy",
    word2: "fresh",
    correct: true,
    translation: "сочный",
  },
  {
    word1: "favour",
    word2: "flour",
    correct: false,
    translation: "услуга",
  },
  {
    word1: "smack",
    word2: "kiss",
    correct: true,
    translation: "целовать",
  },
  {
    word1: "annoy",
    word2: "interrogate",
    correct: false,
    translation: "надоедать",
  },
  {
    word1: "consume",
    word2: "use",
    correct: true,
    translation: "потреблять",
  },
  {
    word1: "hostility",
    word2: "friendship",
    correct: false,
    translation: "вражда",
  },
  {
    word1: "satellite",
    word2: "planet",
    correct: false,
    translation: "спутник",
  },
  {
    word1: "distribute",
    word2: "disseminate",
    correct: true,
    translation: "распределять",
  },
  {
    word1: "trip",
    word2: "travel",
    correct: true,
    translation: "путешествие",
  },
  {
    word1: "contribute",
    word2: "sign",
    correct: false,
    translation: "вкладывать",
  },
  {
    word1: "factory",
    word2: "plant",
    correct: true,
    translation: "завод",
  },
  {
    word1: "equip",
    word2: "seed",
    correct: false,
    translation: "снабжать",
  },
  {
    word1: "wallet",
    word2: "purse",
    correct: true,
    translation: "кошелёк",
  },
  {
    word1: "dead",
    word2: "alive",
    correct: false,
    translation: "мёртвый",
  },
  {
    word1: "amiable",
    word2: "outgoing",
    correct: true,
    translation: "дружелюбный",
  },
  {
    word1: "coffee",
    word2: "brunch",
    correct: false,
    translation: "кофе",
  },
  {
    word1: "society",
    word2: "entity",
    correct: true,
    translation: "общество",
  },
  {
    word1: "play",
    word2: "sing",
    correct: false,
    translation: "играть",
  },
  {
    word1: "slippers",
    word2: "trainers",
    correct: false,
    translation: "шлёпанцы",
  },
  {
    word1: "reach",
    word2: "achieve",
    correct: true,
    translation: "достигать",
  },
  {
    word1: "argue",
    word2: "dispute",
    correct: true,
    translation: "спорить",
  },

  {
    word1: "attention",
    word2: "ignorance",
    correct: false,
    translation: "внимание",
  },
  {
    word1: "dream",
    word2: "wish",
    correct: true,
    translation: "мечта",
  },
  {
    word1: "come",
    word2: "become",
    correct: false,
    translation: "приходить",
  },
  {
    word1: "exclude",
    word2: "miss",
    correct: false,
    translation: "исключать",
  },
  {
    word1: "consolidate",
    word2: "separate",
    correct: false,
    translation: "объединять",
  },
  {
    word1: "fight",
    word2: "brawl",
    correct: true,
    translation: "драка",
  },
  {
    word1: "jab",
    word2: "strike",
    correct: true,
    translation: "ударять",
  },
  {
    word1: "lazy",
    word2: "sluggish",
    correct: true,
    translation: "ленивый",
  },
  {
    word1: "liquid",
    word2: "bottle",
    correct: false,
    translation: "жидкость",
  },
  {
    word1: "caress",
    word2: "fondle",
    correct: true,
    translation: "ласкать",
  },
  {
    word1: "mistaken",
    word2: "concur",
    correct: false,
    translation: "ошибаться",
  },
  {
    word1: "destroy",
    word2: "annihilate",
    correct: true,
    translation: "уничтожать",
  },
  {
    word1: "romantic",
    word2: "friendly",
    correct: false,
    translation: "романтичный",
  },
  {
    word1: "gaze",
    word2: "stare",
    correct: true,
    translation: "gaze",
  },
  {
    word1: "vow",
    word2: "oath",
    correct: true,
    translation: "клятва",
  },
  {
    word1: "skirt",
    word2: "shorts",
    correct: false,
    translation: "юбка",
  },
  {
    word1: "amuse",
    word2: "entertain",
    correct: true,
    translation: "забавлять",
  },
  {
    word1: "park",
    word2: "dine",
    correct: false,
    translation: "парковаться",
  },
  {
    word1: "bother",
    word2: "trouble",
    correct: true,
    translation: "беспокоить",
  },
  {
    word1: "religion",
    word2: "status",
    correct: false,
    translation: "религия",
  },
  {
    word1: "decide",
    word2: "settle",
    correct: true,
    translation: "решать",
  },
  {
    word1: "watch",
    word2: "hunt",
    correct: false,
    translation: "смотреть",
  },
  {
    word1: "heat",
    word2: "warmth",
    correct: true,
    translation: "теплота",
  },
  {
    word1: "cover",
    word2: "zip",
    correct: false,
    translation: "покрывать",
  },
  {
    word1: "direction",
    word2: "route",
    correct: true,
    translation: "направление",
  },
  {
    word1: "race",
    word2: "fight",
    correct: false,
    translation: "гонка",
  },
  {
    word1: "pain",
    word2: "ache",
    correct: true,
    translation: "боль",
  },
  {
    word1: "shift",
    word2: "motion",
    correct: false,
    translation: "смещение",
  },
  {
    word1: "rabbit",
    word2: "bunny",
    correct: true,
    translation: "кролик",
  },
  {
    word1: "permission",
    word2: "allowance",
    correct: true,
    translation: "разрешение",
  },
  {
    word1: "injure",
    word2: "damage",
    correct: true,
    translation: "ранить",
  },
  {
    word1: "decline",
    word2: "approve",
    correct: false,
    translation: "отклонять",
  },
  {
    word1: "smart",
    word2: "intelligent",
    correct: true,
    translation: "остроумный",
  },
  {
    word1: "downtown",
    word2: "countryside",
    correct: false,
    translation: "центр города",
  },
  {
    word1: "develop",
    word2: "improve",
    correct: true,
    translation: "развивать",
  },
  {
    word1: "possibility",
    word2: "evaluation",
    correct: false,
    translation: "возможность",
  },
  {
    word1: "spare",
    word2: "free",
    correct: true,
    translation: "свободный",
  },
  {
    word1: "exceed",
    word2: "agree",
    correct: false,
    translation: "превышать",
  },
  {
    word1: "giggle",
    word2: "laugh",
    correct: true,
    translation: "хихикать",
  },
  {
    word1: "leisure",
    word2: "indolent",
    correct: false,
    translation: "досуг",
  },
  {
    word1: "flat",
    word2: "apartment",
    correct: true,
    translation: "квартира",
  },
  {
    word1: "random",
    word2: "casual",
    correct: true,
    translation: "случайный",
  },
  {
    word1: "colleague",
    word2: "flatmate",
    correct: false,
    translation: "коллега",
  },
  {
    word1: "clear",
    word2: "apparent",
    correct: true,
    translation: "чистый",
  },
  {
    word1: "hardworking",
    word2: "regular",
    correct: false,
    translation: "трудолюбивый",
  },
  {
    word1: "forgetful",
    word2: "oblivious",
    correct: true,
    translation: "забывчивый",
  },
  {
    word1: "idiotic",
    word2: "moronic",
    correct: true,
    translation: "идиотский",
  },
  {
    word1: "grateful",
    word2: "thankful",
    correct: true,
    translation: "благодарный",
  },
  {
    word1: "disturb",
    word2: "assist",
    correct: false,
    translation: "мешать",
  },
  {
    word1: "feel",
    word2: "sense",
    correct: true,
    translation: "чувствовать",
  },
  {
    word1: "mean",
    word2: "denote",
    correct: true,
    translation: "означать",
  },
  {
    word1: "filthy",
    word2: "immaculate",
    correct: false,
    translation: "грязный",
  },
  {
    word1: "suit",
    word2: "costume",
    correct: true,
    translation: "костюм",
  },
  {
    word1: "womanly",
    word2: "natural",
    correct: false,
    translation: "женский",
  },
  {
    word1: "fly",
    word2: "soar",
    correct: true,
    translation: "летать",
  },
  {
    word1: "deafening",
    word2: "earsplitting",
    correct: true,
    translation: "оглушительный",
  },
  {
    word1: "dask",
    word2: "dawn",
    correct: false,
    translation: "закат",
  },
  {
    word1: "ready",
    word2: "prepared",
    correct: true,
    translation: "готовый",
  },
  {
    word1: "unique",
    word2: "simplified",
    correct: false,
    translation: "уникальный",
  },
  {
    word1: "fund",
    word2: "money",
    correct: true,
    translation: "средства",
  },
  {
    word1: "valuable",
    word2: "precious",
    correct: true,
    translation: "ценный",
  },
  {
    word1: "candid",
    word2: "sincere",
    correct: true,
    translation: "искренний",
  },
  {
    word1: "askew",
    word2: "oblique",
    correct: true,
    translation: "косой",
  },
  {
    word1: "helicopter",
    word2: "hopper",
    correct: false,
    translation: "вертолёт",
  },
  {
    word1: "revive",
    word2: "elapse",
    correct: false,
    translation: "возрождать",
  },
  {
    word1: "translate",
    word2: "interpret",
    correct: true,
    translation: "переводить",
  },
  {
    word1: "artificial",
    word2: "realistic",
    correct: false,
    translation: "искусственный",
  },
  {
    word1: "yummy",
    word2: "delicious",
    correct: true,
    translation: "вкусный",
  },
  {
    word1: "talkative",
    word2: "genuine",
    correct: false,
    translation: "общительный",
  },
  {
    word1: "resuscitate",
    word2: "animate",
    correct: true,
    translation: "оживлять",
  },
  {
    word1: "fence",
    word2: "pain",
    correct: false,
    translation: "забор",
  },
  {
    word1: "courtyard",
    word2: "insight",
    correct: false,
    translation: "двор",
  },
  {
    word1: "irate",
    word2: "grumpy",
    correct: true,
    translation: "сердитый",
  },
  {
    word1: "grass",
    word2: "cloud",
    correct: false,
    translation: "трава",
  },
  {
    word1: "intelligence",
    word2: "wit",
    correct: true,
    translation: "интеллект",
  },
  {
    word1: "cyber",
    word2: "suitable",
    correct: false,
    translation: "кибер",
  },
  {
    word1: "prayer",
    word2: "oath",
    correct: false,
    translation: "молитва",
  },
  {
    word1: "delegate",
    word2: "entrust",
    correct: true,
    translation: "делегировать",
  },
  {
    word1: "draw",
    word2: "paint",
    correct: true,
    translation: "рисовать",
  },
  {
    word1: "arouse",
    word2: "excite",
    correct: true,
    translation: "возбуждать",
  },
  {
    word1: "arm",
    word2: "knee",
    correct: false,
    translation: "рука",
  },
  {
    word1: "nail",
    word2: "coffin",
    correct: false,
    translation: "гвоздь",
  },
  {
    word1: "duty",
    word2: "doubt",
    correct: false,
    translation: "режим",
  },
  {
    word1: "ocean",
    word2: "picture",
    correct: false,
    translation: "океан",
  },
  {
    word1: "candle",
    word2: "zoom",
    correct: true,
    translation: "свеча",
  },
  {
    word1: "speak",
    word2: "converse",
    correct: false,
    translation: "говорить",
  },
  {
    word1: "awkward",
    word2: "clumsy",
    correct: true,
    translation: "неуклюжий",
  },
  {
    word1: "lipstick",
    word2: "makeup",
    correct: false,
    translation: "помада",
  },
  {
    word1: "underrated",
    word2: "misjudged",
    correct: true,
    translation: "недооценённый",
  },
  {
    word1: "danger",
    word2: "warning",
    correct: false,
    translation: "опасность",
  },
  {
    word1: "mammal",
    word2: "pregnant",
    correct: false,
    translation: "млекопитающее",
  },
  {
    word1: "serious",
    word2: "grave",
    correct: true,
    translation: "серьёзный",
  },
  {
    word1: "darling",
    word2: "fair",
    correct: false,
    translation: "дорогой",
  },
  {
    word1: "tough",
    word2: "severe",
    correct: true,
    translation: "жёсткий",
  },
  {
    word1: "grappling",
    word2: "wrestling",
    correct: true,
    translation: "борьба",
  },
  {
    word1: "ox",
    word2: "deer",
    correct: false,
    translation: "бык",
  },
  {
    word1: "investigate",
    word2: "explore",
    correct: true,
    translation: "расследовать",
  },
  {
    word1: "blueberry",
    word2: "watermelon",
    correct: false,
    translation: "голубика",
  },
  {
    word1: "seldom",
    word2: "rarely",
    correct: true,
    translation: "редко",
  },
  {
    word1: "secret",
    word2: "undercover",
    correct: true,
    translation: "тайный",
  },
  {
    word1: "elevator",
    word2: "conductor",
    correct: false,
    translation: "подъёмник",
  },
  {
    word1: "puzzle",
    word2: "riddle",
    correct: true,
    translation: "загадка",
  },
  {
    word1: "miniscule",
    word2: "tiny",
    correct: true,
    translation: "крошечный",
  },
  {
    word1: "retarded",
    word2: "psycho",
    correct: false,
    translation: "умственно-отсталый",
  },
  {
    word1: "drug",
    word2: "vitamin",
    correct: false,
    translation: "таблетка",
  },
  {
    word1: "vagabond",
    word2: "slacker",
    correct: true,
    translation: "бездельник",
  },
  {
    word1: "insurgent",
    word2: "rebellious",
    correct: true,
    translation: "восставший",
  },
  {
    word1: "soccer",
    word2: "football",
    correct: true,
    translation: "футбол",
  },
  {
    word1: "savage",
    word2: "sweetheart",
    correct: false,
    translation: "дикарь",
  },
  {
    word1: "care",
    word2: "ignore",
    correct: false,
    translation: "заботиться",
  },
  {
    word1: "shoulder",
    word2: "arm",
    correct: false,
    translation: "плечо",
  },
  {
    word1: "slave",
    word2: "hostage",
    correct: false,
    translation: "раб",
  },
  {
    word1: "vibrant",
    word2: "colorful",
    correct: true,
    translation: "графический",
  },
  {
    word1: "miner",
    word2: "programmer",
    correct: false,
    translation: "шахтёр",
  },
  {
    word1: "lubricant",
    word2: "oil",
    correct: true,
    translation: "смазка",
  },
  {
    word1: "tire",
    word2: "round",
    correct: false,
    translation: "шина",
  },
  {
    word1: "gay",
    word2: "homosexual",
    correct: true,
    translation: "гей",
  },
  {
    word1: "chasing",
    word2: "pursuit",
    correct: true,
    translation: "преследование",
  },
  {
    word1: "supplementary",
    word2: "additional",
    correct: true,
    translation: "дополнительный",
  },
  {
    word1: "delight",
    word2: "hatred",
    correct: false,
    translation: "восхищение",
  },
  {
    word1: "script",
    word2: "scenario",
    correct: true,
    translation: "сценарий",
  },
  {
    word1: "dance",
    word2: "move",
    correct: false,
    translation: "танцевать",
  },
  {
    word2: "biased",
    word1: "neutral",
    correct: false,
    translation: "необъективный",
  },
  {
    word1: "furnish",
    word2: "supply",
    correct: true,
    translation: "снабжать",
  },
];

export default wordStock;
